aaron-bond.better-comments
akamud.vscode-theme-onedark
Arjun.swagger-viewer
auchenberg.vscode-browser-preview
batisteo.vscode-django
bradgashler.htmltagwrap
ChakrounAnas.turbo-console-log
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
cmstead.jsrefactor
CoenraadS.bracket-pair-colorizer-2
dbaeumer.vscode-eslint
deerawan.vscode-dash
donjayamanne.githistory
donjayamanne.python-extension-pack
drKnoxy.eslint-disable-snippets
dsznajder.es7-react-js-snippets
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
firefox-devtools.vscode-firefox-debug
flowtype.flow-for-vscode
formulahendry.auto-rename-tag
formulahendry.code-runner
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
Gruntfuggly.todo-tree
KnisterPeter.vscode-github
letrieu.expand-region
magicstack.MagicPython
maty.vscode-mocha-sidebar
mechatroner.rainbow-csv
mgmcdermott.vscode-language-babel
ms-azuretools.vscode-docker
ms-dotnettools.csharp
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
oderwat.indent-rainbow
philsinatra.nested-comments
PKief.material-icon-theme
planbcoding.vscode-react-refactor
pnp.polacode
quicktype.quicktype
rbbit.typescript-hero
redhat.vscode-yaml
ritwickdey.create-file-folder
ritwickdey.live-sass
ritwickdey.LiveServer
shd101wyy.markdown-preview-enhanced
sleistner.vscode-fileutils
streetsidesoftware.code-spell-checker
TabNine.tabnine-vscode
Tyriar.lorem-ipsum
vincaslt.highlight-matching-tag
VisualStudioExptTeam.vscodeintellicode
wangtao0101.vscode-js-import
wholroyd.jinja
wix.vscode-import-cost
wmaurer.change-case
xabikos.JavaScriptSnippets
zhuangtongfa.material-theme
